version: '2'
services:
    base-python:
        build: .
    rabbitmq:
        image: rabbitmq:management
        ports:
            - 8080:15672
    server:
        extends: base-python
        command: ["./wait-for-it.sh", "-t", "30", "rabbitmq:5672", "--", "python", "-u", "rpc_server.py"]
        links:
            - rabbitmq
    client:
        extends: base-python
        command: ["./wait-for-it.sh", "-t", "30", "rabbitmq:5672", "--", "python", "-u", "rpc_client.py"]
        links:
            - rabbitmq
